apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/component": "jenkins-master"
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: jenkins
    name: jenkins-master-pvc
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/jenkins-master